name: Coverity Scan
on:
  schedule:
    - cron: '0 23 * * *' # Daily at 23:00 UTC
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt install autoconf automake bison build-essential \
            libevent-dev libssl-dev libtool pkgconf libpam0g-dev zlib1g-dev
    - name: scan
      run: sh ci/scripts/coverity_scan.sh
      env:
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
